version: '3.9'

services:
  app:
    build: .
    container_name: ts-node
    ports:
      - 8888:8888
    volumes:
      - ./:/usr/src/app:delegated
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
